scarab:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  br_arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: br_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  bl_arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: bl_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fr_arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: fr_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fl_arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: fl_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  br_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: br_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  bl_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: bl_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fr_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fr_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fl_wheel_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fl_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
